# Generated by Django 5.0.6 on 2024-06-14 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Customar',
        ),
    ]
