# Generated by Django 5.0.6 on 2024-06-18 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_customer_order_customar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customar',
            new_name='customer',
        ),
    ]
