# Generated by Django 5.0.6 on 2024-06-19 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_customar_order_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customar',
            new_name='Customer',
        ),
    ]
